"""Standalone tracer-bullet smoke test for the ``garminconnect`` workout API.

This script is intentionally **not** part of the MCP server. It exists to shake
out the live Garmin Connect calls (auth, upload, schedule, list, unschedule,
delete) before the wrapper layer in T07+ commits to a particular API surface.

What it does (idempotent, in order):

1. Load Garmin tokens via ``Garmin().login(tokenstore=...)``. T02's bootstrap
   must have already populated ``--token-dir`` (default ``~/.garminconnect``).
2. Pre-clean: list workouts in the library and delete any prior copies whose
   name matches ``--workout-name``. This makes the script safe to re-run after
   a partial failure.
3. Build a small running workout: 5-min warmup (time, no target), 10-min
   interval @ HR 141-155 (heart-rate-zone target), 5-min cooldown.
4. Upload via ``Garmin.upload_running_workout``; capture ``workout_id``.
5. Schedule via ``Garmin.schedule_workout`` for ``today + --days-out`` days
   interpreted in Africa/Tunis. Capture ``scheduled_id`` from the response.
6. Verify with ``Garmin.get_scheduled_workouts`` for that month — there must be
   exactly one matching calendar item on the target date.
7. Tear down: ``unschedule_workout`` then ``delete_workout``.
8. Re-list and assert nothing remains for the target date.

Run with::

    uv run python -m scripts.tracer
    uv run python -m scripts.tracer --token-dir /path/to/tokens --days-out 60

The repo owner runs this manually against real Garmin; the script has no unit
coverage for the live HTTP path. The helper that builds the workout dict is
unit-tested in ``tests/unit/test_tracer.py``.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date, timedelta
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from garminconnect import (
    Garmin,
    GarminConnectAuthenticationError,
    GarminConnectConnectionError,
    GarminConnectTooManyRequestsError,
)
from garminconnect.workout import (
    RunningWorkout,
    WorkoutSegment,
    create_cooldown_step,
    create_interval_step,
    create_warmup_step,
)

DEFAULT_TOKEN_DIR = Path.home() / ".garminconnect"
DEFAULT_DAYS_OUT = 60
DEFAULT_WORKOUT_NAME = "Tracer bullet"
USER_TIMEZONE = "Africa/Tunis"

WARMUP_SECONDS = 5 * 60
INTERVAL_SECONDS = 10 * 60
COOLDOWN_SECONDS = 5 * 60
INTERVAL_HR_MIN = 141
INTERVAL_HR_MAX = 155


def _hr_zone_target(min_bpm: int, max_bpm: int) -> dict[str, Any]:
    """Build a heart-rate-zone target dict for an executable step.

    Mirrors DESIGN.md §7. The package's ``create_*_step`` helpers accept a
    ``target_type`` dict and pass it through verbatim, so we construct the HR
    target by hand here rather than waiting for typed helpers that don't exist.
    """
    return {
        "workoutTargetTypeId": 4,
        "workoutTargetTypeKey": "heart.rate.zone",
        "displayOrder": 4,
        "targetValueOne": min_bpm,
        "targetValueTwo": max_bpm,
    }


def build_tracer_workout(name: str = DEFAULT_WORKOUT_NAME) -> RunningWorkout:
    """Construct the tracer workout: warmup → HR interval → cooldown.

    No repeats, no distance-based steps — just the minimum surface needed to
    confirm the upload/schedule/teardown round-trip works.
    """
    warmup = create_warmup_step(duration_seconds=float(WARMUP_SECONDS), step_order=1)
    interval = create_interval_step(
        duration_seconds=float(INTERVAL_SECONDS),
        step_order=2,
        target_type=_hr_zone_target(INTERVAL_HR_MIN, INTERVAL_HR_MAX),
    )
    cooldown = create_cooldown_step(duration_seconds=float(COOLDOWN_SECONDS), step_order=3)

    segment = WorkoutSegment(
        segmentOrder=1,
        sportType={"sportTypeId": 1, "sportTypeKey": "running", "displayOrder": 1},
        workoutSteps=[warmup, interval, cooldown],
    )
    total_seconds = WARMUP_SECONDS + INTERVAL_SECONDS + COOLDOWN_SECONDS
    description = f"[mcp] tracer bullet — autogenerated by scripts/tracer.py ({total_seconds}s)"
    return RunningWorkout(
        workoutName=name,
        estimatedDurationInSecs=total_seconds,
        workoutSegments=[segment],
        description=description,
    )


def target_date(days_out: int, tz_name: str = USER_TIMEZONE) -> date:
    """Return ``today + days_out`` in the configured timezone."""
    today = date.today() if tz_name is None else _today_in(tz_name)
    return today + timedelta(days=days_out)


def _today_in(tz_name: str) -> date:
    """``date.today()`` evaluated in ``tz_name`` rather than the system zone."""
    from datetime import datetime

    return datetime.now(tz=ZoneInfo(tz_name)).date()


def _extract_workout_id(upload_response: dict[str, Any]) -> int:
    """Pull the workout id out of the upload response.

    Garmin's response shape uses ``workoutId`` at the top level. We accept a few
    plausible aliases defensively so the script doesn't silently fail if Garmin
    tweaks the envelope.
    """
    for key in ("workoutId", "id", "workout_id"):
        if key in upload_response and upload_response[key] is not None:
            return int(upload_response[key])
    raise RuntimeError(
        f"Upload response did not contain a workout id; got keys={sorted(upload_response)}"
    )


def _extract_scheduled_id(schedule_response: dict[str, Any]) -> int:
    """Pull the scheduled-workout id out of the schedule response.

    Garmin returns ``workoutScheduleId`` here. Same defensive lookup pattern as
    the upload helper above.
    """
    for key in ("workoutScheduleId", "scheduledWorkoutId", "id"):
        if key in schedule_response and schedule_response[key] is not None:
            return int(schedule_response[key])
    raise RuntimeError(
        f"Schedule response did not contain a schedule id; got keys={sorted(schedule_response)}"
    )


def _iter_calendar_items(month_response: Any) -> list[dict[str, Any]]:
    """Yield calendar items from ``get_scheduled_workouts``'s response.

    Garmin wraps the items under a key (commonly ``calendarItems``) but we have
    not pinned the exact envelope — we handle dict-with-list and bare-list
    shapes so the script remains useful on minor server-side changes.
    """
    if isinstance(month_response, list):
        return [item for item in month_response if isinstance(item, dict)]
    if isinstance(month_response, dict):
        for key in ("calendarItems", "items", "scheduledWorkouts"):
            candidate = month_response.get(key)
            if isinstance(candidate, list):
                return [item for item in candidate if isinstance(item, dict)]
    return []


def find_scheduled_on_date(client: Garmin, target: date) -> list[dict[str, Any]]:
    """Return all calendar items scheduled exactly on ``target``."""
    month_payload = client.get_scheduled_workouts(year=target.year, month=target.month)
    iso = target.isoformat()
    out: list[dict[str, Any]] = []
    for item in _iter_calendar_items(month_payload):
        if item.get("date") == iso or item.get("scheduledDate") == iso:
            out.append(item)
    return out


def cleanup_prior_tracers(client: Garmin, name: str) -> int:
    """Delete any leftover library workouts whose name matches ``name``.

    Returns the count deleted. Idempotency safeguard: a previous run that
    crashed between upload and teardown leaves a "Tracer bullet" template (and
    possibly a schedule entry) on the account; we remove both before building a
    new one so the script can re-run cleanly.
    """
    deleted = 0
    workouts = client.get_workouts(start=0, limit=100)
    if not isinstance(workouts, list):
        return 0
    for workout in workouts:
        if not isinstance(workout, dict):
            continue
        if workout.get("workoutName") != name:
            continue
        workout_id = workout.get("workoutId") or workout.get("id")
        if workout_id is None:
            continue
        # Unschedule any calendar instances first; deleting a scheduled workout
        # leaves a dangling calendar entry otherwise.
        _unschedule_all_for_workout(client, int(workout_id))
        client.delete_workout(int(workout_id))
        deleted += 1
    return deleted


def _unschedule_all_for_workout(client: Garmin, workout_id: int) -> None:
    """Remove every scheduled instance of ``workout_id`` from the calendar.

    Scans the current month and the following two months — enough to cover the
    default 60-day window plus a safety margin around month boundaries.
    """
    today = _today_in(USER_TIMEZONE)
    months_to_scan = {(today.year, today.month)}
    for offset in (1, 2, 3):
        future = today + timedelta(days=offset * 30)
        months_to_scan.add((future.year, future.month))

    for year, month in months_to_scan:
        payload = client.get_scheduled_workouts(year=year, month=month)
        for item in _iter_calendar_items(payload):
            if int(item.get("workoutId", 0) or 0) != workout_id:
                continue
            scheduled_id = item.get("workoutScheduleId") or item.get("scheduledWorkoutId")
            if scheduled_id is None:
                continue
            client.unschedule_workout(int(scheduled_id))


def run_tracer(
    token_dir: Path,
    days_out: int,
    workout_name: str,
) -> int:
    """Execute the full tracer sequence. Returns process exit code (0 on success)."""
    if not (token_dir / "garmin_tokens.json").exists():
        print(
            f"No Garmin tokens at {token_dir}/garmin_tokens.json. "
            "Run `uv run python -m scripts.garmin_bootstrap` first.",
            file=sys.stderr,
        )
        return 1

    client = Garmin()
    client.login(tokenstore=str(token_dir))
    print(f"Garmin login OK (tokens at {token_dir}).")

    cleaned = cleanup_prior_tracers(client, workout_name)
    if cleaned:
        print(f"Pre-clean: removed {cleaned} prior '{workout_name}' workout(s).")

    workout = build_tracer_workout(workout_name)
    upload_response = client.upload_running_workout(workout)
    workout_id = _extract_workout_id(upload_response)
    print(f"Uploaded workout: workout_id={workout_id}")

    target = target_date(days_out)
    schedule_response = client.schedule_workout(workout_id, target.isoformat())
    scheduled_id = _extract_scheduled_id(schedule_response)
    print(f"Scheduled for {target.isoformat()}: scheduled_id={scheduled_id}")

    matches = find_scheduled_on_date(client, target)
    matching_ids = [
        int(m.get("workoutScheduleId") or m.get("scheduledWorkoutId") or 0) for m in matches
    ]
    if scheduled_id not in matching_ids:
        print(
            f"FAIL: scheduled_id {scheduled_id} not found in calendar listing "
            f"for {target.isoformat()}; got ids={matching_ids}",
            file=sys.stderr,
        )
        # Best-effort teardown so we don't leak state on failure.
        client.unschedule_workout(scheduled_id)
        client.delete_workout(workout_id)
        return 4
    print(f"Calendar listing confirmed {len(matches)} entry/entries on {target.isoformat()}.")

    client.unschedule_workout(scheduled_id)
    print(f"Unscheduled {scheduled_id}.")
    client.delete_workout(workout_id)
    print(f"Deleted workout {workout_id}.")

    leftovers = [
        m
        for m in find_scheduled_on_date(client, target)
        if int(m.get("workoutScheduleId") or m.get("scheduledWorkoutId") or 0) == scheduled_id
    ]
    if leftovers:
        print(
            f"FAIL: scheduled_id {scheduled_id} still present after teardown.",
            file=sys.stderr,
        )
        return 5
    print("Post-teardown listing is clean. Tracer bullet succeeded.")
    return 0


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Garmin Connect tracer-bullet smoke test (T04).",
    )
    parser.add_argument(
        "--token-dir",
        type=Path,
        default=DEFAULT_TOKEN_DIR,
        help=f"Directory holding garmin_tokens.json (default: {DEFAULT_TOKEN_DIR}).",
    )
    parser.add_argument(
        "--days-out",
        type=int,
        default=DEFAULT_DAYS_OUT,
        help=f"How many days in the future to schedule (default: {DEFAULT_DAYS_OUT}).",
    )
    parser.add_argument(
        "--workout-name",
        default=DEFAULT_WORKOUT_NAME,
        help=f"Workout template name (default: {DEFAULT_WORKOUT_NAME!r}).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint. Returns process exit code."""
    args = _parse_args(argv)
    token_dir: Path = args.token_dir.expanduser()
    if args.days_out <= 0:
        print("--days-out must be positive.", file=sys.stderr)
        return 2

    try:
        return run_tracer(
            token_dir=token_dir,
            days_out=args.days_out,
            workout_name=args.workout_name,
        )
    except GarminConnectAuthenticationError as exc:
        print(f"Garmin auth failed: {exc}", file=sys.stderr)
        return 1
    except GarminConnectTooManyRequestsError as exc:
        print(f"Garmin rate-limited the tracer: {exc}", file=sys.stderr)
        return 2
    except GarminConnectConnectionError as exc:
        print(f"Garmin connection error: {exc}", file=sys.stderr)
        return 3
    except KeyboardInterrupt:
        print("\nAborted by user.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
